// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGgRJNK1THVOM9EhYotqsfKnbVPL4b_Rc',
    appId: '1:537075220409:web:c51dbbd2a1fd52173d8068',
    messagingSenderId: '537075220409',
    projectId: 'proyecto-movil-e9cca',
    authDomain: 'proyecto-movil-e9cca.firebaseapp.com',
    storageBucket: 'proyecto-movil-e9cca.appspot.com',
    measurementId: 'G-VW5ECRLP4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfYUgq18QMtyJEr3srvtNiN_F7Md4pclA',
    appId: '1:537075220409:android:c92fa494a06bc9ac3d8068',
    messagingSenderId: '537075220409',
    projectId: 'proyecto-movil-e9cca',
    storageBucket: 'proyecto-movil-e9cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeimLNhXpaOPFK9_mzfGp4tx4oaAUCMxc',
    appId: '1:537075220409:ios:573c91ee564da6273d8068',
    messagingSenderId: '537075220409',
    projectId: 'proyecto-movil-e9cca',
    storageBucket: 'proyecto-movil-e9cca.appspot.com',
    iosBundleId: 'com.example.proyectoMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeimLNhXpaOPFK9_mzfGp4tx4oaAUCMxc',
    appId: '1:537075220409:ios:9d1f4a1b002839ad3d8068',
    messagingSenderId: '537075220409',
    projectId: 'proyecto-movil-e9cca',
    storageBucket: 'proyecto-movil-e9cca.appspot.com',
    iosBundleId: 'com.example.proyectoMovil.RunnerTests',
  );
}
